### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Jojo144** [artus40/djangoapp_ynh#1]
It would be very good to have such a package!
I could help but my knowings in yunohost and django are very limited.

I tried to install it on a VM, and I encountered the following issues:

1. My version of Yunohost was not recent enough (need >= 2.6.4 for one of the helpers)

2. The command `ynh_install_app_dependencies python3 virtualenv git` fails with "Invalid control file"
(I temporarily manually installed the dependencies and commented this line)

3. Te command `source "${venv}/bin/activate"` fails with "Warning: /var/www/my_djangoapp/env/bin/activate: line 8: _OLD_VIRTUAL_PATH: unbound variable"
I can fix it with something like
```
set +o nounset
. ~/.env/bin/activate
set -o nounset
```
(taken here https://github.com/pypa/virtualenv/issues/150)

4. The command `django admin ...` fails with "Warning: CommandError: Destination directory '/var/www/my_djangoapp/app' does not exist, please create it first."
I fixed it adding some `mkdir`s.

5. Then it got stuck on the creation of the django superuser.

I tried your las commit https://github.com/artus40/djangoapp_ynh/commit/299fe503c34f72d074d8e56ea24a2de439c44d37 (with my temorary fixes) but it fails with "WARNING ./install: line 104: setup_django: command not found".

**Comment by artus40** [comment]
Thanks for your interest ! 
I know little myself and actually learn on the way :)

You've realized i think it is a work in progress, i actually didn't even run it in a VM yet. I'm testing django related scripts on my desktop computer for now.
Still, the 4. and 5. should be resolved by my last commits.

Regarding 1., i copied an old manifest.json file from [my_webapp_ynh](https://github.com/YunoHost-Apps/my_webapp_ynh) a while back, it would be better to just get the new version but i didn't get to that since i can't test it yet anyway.
I dont understand 2. at all, maybe the answers are inside ynh_install_app_dependencies declaration ?

Finally, 3. thanks for this great tip !
I'm not sure about my design though, is it necessary to activate/deactivate inside all venv related functions or is it better to just use the binaries full paths ?

Anyway, thanks again for your help ! Feel free to contribute, i'm also new to collaboration with git, but will gladly learn how to manage some pull requests :)

**Comment by artus40** [comment]
I found time to make some huge progress. It is still work-in-progress but should be much easier to test out.
The package.py script should help to build a brand new Yunohost app from any locally-working django project.

I've been testing it inside a VM and installation now completes !
